name: ml_sentiment_simple
description: >
  A simple multilingual (Turkish + English) sentiment analyzer based on word scoring.
version: 1.0.0
homepage: https://github.com/yourusername/ml_sentiment_simple
repository: https://github.com/yourusername/ml_sentiment_simple

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:

dev_dependencies:
  test: ^1.24.0
